/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;

import com.mycompany.maven.app.enumeration.GenderType;
import com.mycompany.maven.app.Koneksi;
import com.mycompany.maven.app.model.Doctor;
import com.mycompany.maven.app.model.SpecializeDoctor;
import com.mycompany.maven.app.service.DoctorServiceImpl;
import com.mycompany.maven.app.service.SpecializeDoctorServiceImpl;
import com.mycompany.maven.app.util.UpdatableBCrypt;
import com.mycompany.maven.app.util.ComboItem;
import java.io.File;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.HibernateException;
    
/**
 *
 * @author mac
 */
public class DokterPanel extends javax.swing.JPanel {
    private String editedId = "";
    private final DoctorServiceImpl doctorService;
    private final UpdatableBCrypt bcrypt;
    private final MainFrame mainFrame;
    private final SpecializeDoctorServiceImpl specializeDoctorServiceImpl;

    /**
     * Creates new form DokterPanel
     */
    public DokterPanel(
        UpdatableBCrypt bcrypt,
        DoctorServiceImpl doctorService,
        MainFrame mainFrame,
        SpecializeDoctorServiceImpl specializeDoctorServiceImpl
    ) {
        initComponents();
        this.doctorService = doctorService;
        this.bcrypt = bcrypt;
        this.mainFrame = mainFrame;
        this.specializeDoctorServiceImpl = specializeDoctorServiceImpl;
        getDataTable();
        getSpecializes();
        PasswordTitle.setVisible(false);
        PasswordInput.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Forms = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StrField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        BirthDatePicker = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        GenderSelect = new javax.swing.JComboBox<>();
        SpecializationSelect = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressField = new javax.swing.JTextPane();
        PasswordCheck = new javax.swing.JCheckBox();
        PasswordInput = new javax.swing.JPasswordField();
        PasswordTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        Buttons = new javax.swing.JPanel();
        ListSpecialistButton = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JToggleButton();
        SaveButton = new javax.swing.JButton();
        TableContainer = new javax.swing.JPanel();
        TableScroll = new javax.swing.JScrollPane();
        TableDoctor = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Body.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("No Str");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Nama ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal Lahir");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Alamat");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        BirthDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BirthDatePickerPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Spesialis");

        GenderSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenderSelect.setModel(new javax.swing.DefaultComboBoxModel<>(GenderType.values()));

        SpecializationSelect.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jScrollPane1.setViewportView(AddressField);

        PasswordCheck.setText("Masukan Password ?");
        PasswordCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PasswordCheckItemStateChanged(evt);
            }
        });
        PasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCheckActionPerformed(evt);
            }
        });

        PasswordTitle.setText("Password");

        jLabel1.setText("Email");

        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });

        jLabel2.setText("No. Telepon");

        javax.swing.GroupLayout FormsLayout = new javax.swing.GroupLayout(Forms);
        Forms.setLayout(FormsLayout);
        FormsLayout.setHorizontalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StrField)
                    .addComponent(NameField)
                    .addComponent(BirthDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(PhoneField))
                .addGap(53, 53, 53)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordCheck)
                    .addGroup(FormsLayout.createSequentialGroup()
                        .addComponent(PasswordTitle)
                        .addGap(34, 34, 34)
                        .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormsLayout.createSequentialGroup()
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailInput)
                            .addComponent(GenderSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecializationSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        FormsLayout.setVerticalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(SpecializationSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(StrField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(GenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(PasswordCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordTitle)
                            .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(BirthDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Body.add(Forms, java.awt.BorderLayout.CENTER);

        Buttons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        ListSpecialistButton.setText("Daftar Spesialisasi");
        ListSpecialistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListSpecialistButtonMouseClicked(evt);
            }
        });
        ListSpecialistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListSpecialistButtonActionPerformed(evt);
            }
        });
        Buttons.add(ListSpecialistButton);

        Print.setText("Cetak");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        Buttons.add(Print);

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        Buttons.add(ResetButton);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        Buttons.add(RefreshButton);

        RemoveButton.setText("Hapus");
        RemoveButton.setVisible(false);
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        Buttons.add(RemoveButton);

        SaveButton.setText("Simpan");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        Buttons.add(SaveButton);

        Body.add(Buttons, java.awt.BorderLayout.SOUTH);

        add(Body, java.awt.BorderLayout.CENTER);

        TableContainer.setLayout(new java.awt.BorderLayout());

        TableScroll.setPreferredSize(new java.awt.Dimension(452, 202));

        TableDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "STR", "Nama", "Tgl Lahir", "Spesialis", "Jen Kel", "Alamat", "dibuat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDoctor.removeColumn(TableDoctor.getColumnModel().getColumn(0));
        TableDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDoctorMouseClicked(evt);
            }
        });
        TableScroll.setViewportView(TableDoctor);

        TableContainer.add(TableScroll, java.awt.BorderLayout.CENTER);

        add(TableContainer, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public void getDataTable() {
        DefaultTableModel tm = (DefaultTableModel) TableDoctor.getModel();
        tm.setRowCount(0);
        try {
            for (Doctor next : this.doctorService.findAll()) {
                Object[] newRow = {
                    next.getId(),
                    next.getStrNumber(),
                    next.getName(),
                    next.getBirthDate(),
                    next.getSpecialize().getName(),
                    next.getGender(),
                    next.getAddress(),
                    next.getCreatedAt()
                };
                tm.addRow(newRow);
            }
        } catch (HibernateException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    
    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void BirthDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BirthDatePickerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDatePickerPropertyChange

    private void getSpecializes() {
        List<SpecializeDoctor> specialize = specializeDoctorServiceImpl.findAll();
        SpecializationSelect.removeAllItems();
        for (SpecializeDoctor sd : specialize) {
            SpecializationSelect.addItem(new ComboItem(sd.getName(), sd.getId()));
        }
    }
    
    private void refreshTable() {
        DefaultTableModel tm = (DefaultTableModel) TableDoctor.getModel();
        getDataTable();
        tm.fireTableDataChanged();
        TableDoctor.repaint();
    }
    
    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        refreshTable();
        getSpecializes();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        Doctor dokter = new Doctor();
        dokter.setStrNumber(StrField.getText());
        dokter.setName(NameField.getText());
        dokter.setBirthDate(BirthDatePicker.getDate());
        dokter.setAddress(AddressField.getText());
        GenderType selectedType = (GenderType) GenderSelect.getSelectedItem();
        dokter.setGender(selectedType);
        ComboItem item = (ComboItem) SpecializationSelect.getSelectedItem();
        String specializeId = item.getValue();
        dokter.setSpecializeDoctorId(specializeId);
        dokter.setEmail(EmailInput.getText());
        dokter.setPhone(PhoneField.getText());
        if (PasswordCheck.isSelected()) {
            dokter.setPassword(bcrypt.hash(new String(PasswordInput.getPassword())));
        }
        boolean isSaved = false;
        if (editedId.isEmpty()) {
            isSaved = doctorService.insert(dokter);    
        } else {
            dokter.setId(editedId);
            isSaved = doctorService.update(dokter);
        }
        
        if (isSaved) {
            resetForm();
            JOptionPane.showMessageDialog(this, "Berhasil disimpan!");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal disimpan!");
        }
        refreshTable();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void resetForm() {
        StrField.setText("");
        NameField.setText("");
        BirthDatePicker.setCalendar(null);
        AddressField.setText("");
        GenderSelect.setSelectedIndex(0);
        SpecializationSelect.setSelectedIndex(0);
        EmailInput.setText("");
        PhoneField.setText("");
        PasswordInput.setText("");
        PasswordCheck.setSelected(false);
        this.editedId = "";
        this.RemoveButton.setVisible(false);
        getSpecializes();
    }
    
    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_ResetButtonActionPerformed
    public static java.util.Calendar toCalendar(java.util.Date date){ 
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        return cal;
    }
    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showOptionDialog(
                this,
                "Anda Yakin?",
                "Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, 
                null,
                null,
                null
        );
        if (confirm == JOptionPane.YES_OPTION) {
            doctorService.delete(editedId);
            resetForm();
            refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil dihapus!");
        }
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        String filename = System.getProperty("user.dir") + File.separator + 
                "src" + File.separator + "main" + File.separator + "java" +
                File.separator + "com" + File.separator + "mycompany" + File.separator +
                "maven" + File.separator + "app" + File.separator + "report" + File.separator +
                "report-doctor-potrait.jrxml";
        Map<String, Object> kode = new HashMap<String, Object>();
        kode.put("username", mainFrame.getAuthentication().getName());
        kode.put("role", mainFrame.getAuthentication().getRoleText());
        kode.put(JRParameter.REPORT_LOCALE, new Locale( "id", "ID" ));
        File report = new File(filename);
        try {
            Koneksi conn = new Koneksi();
            JasperDesign jasDes = JRXmlLoader.load(report);
            JasperReport jasRep = JasperCompileManager.compileReport(jasDes);
            JasperPrint jasPri = JasperFillManager.fillReport(jasRep, kode, conn.connect());
            JasperViewer.viewReport(jasPri, false);

        } catch (Exception e) {
            System.out.println("err: " + e.getMessage());
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void PasswordCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PasswordCheckItemStateChanged
        // TODO add your handling code here:
        PasswordInput.setText(null);
        if (evt.getStateChange() == 1) {
            PasswordTitle.setVisible(true);
            PasswordInput.setVisible(true);
        } else {
            PasswordInput.setVisible(false);
            PasswordTitle.setVisible(false);
        }
    }//GEN-LAST:event_PasswordCheckItemStateChanged

    private void PasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordCheckActionPerformed

    private void ListSpecialistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListSpecialistButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ListSpecialistButtonMouseClicked

    private void ListSpecialistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListSpecialistButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.navigate("specializeDoctor");
    }//GEN-LAST:event_ListSpecialistButtonActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void TableDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDoctorMouseClicked
        // TODO add your handling code here:
        int row = TableDoctor.getSelectedRow();
        this.editedId = TableDoctor.getModel().getValueAt(row, 0).toString();
        Doctor myDoctor = this.doctorService.findById(editedId);
        StrField.setText(myDoctor.getStrNumber());
        NameField.setText(myDoctor.getName());
        BirthDatePicker.setDate(myDoctor.getBirthDate());
        SpecializationSelect.getModel().setSelectedItem(
            new ComboItem(myDoctor.getSpecialize().getName(), myDoctor.getSpecialize().getId())
        );
        GenderSelect.getModel().setSelectedItem(myDoctor.getGender());
        AddressField.setText(myDoctor.getAddress());
        PhoneField.setText(myDoctor.getPhone());
        EmailInput.setText(myDoctor.getEmail());
        this.RemoveButton.setVisible(true);
    }//GEN-LAST:event_TableDoctorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AddressField;
    private com.toedter.calendar.JDateChooser BirthDatePicker;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Buttons;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JPanel Forms;
    private javax.swing.JComboBox<GenderType> GenderSelect;
    private javax.swing.JButton ListSpecialistButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JCheckBox PasswordCheck;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton Print;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JToggleButton RemoveButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox<ComboItem> SpecializationSelect;
    private javax.swing.JTextField StrField;
    private javax.swing.JPanel TableContainer;
    private javax.swing.JTable TableDoctor;
    private javax.swing.JScrollPane TableScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
