/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;

import com.mycompany.maven.app.model.Laboratorium;
import com.mycompany.maven.app.model.LaboratoriumDivision;
import com.mycompany.maven.app.service.LabDivisionServiceImpl;
import com.mycompany.maven.app.service.LaboratoriumServiceImpl;
import com.mycompany.maven.app.util.ComboItem;
import com.mycompany.maven.app.util.UpdatableBCrypt;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class LaboratoriumPanel extends javax.swing.JPanel {

    private final LaboratoriumServiceImpl labService = new LaboratoriumServiceImpl();
    private final LabDivisionServiceImpl labDivisionService = new LabDivisionServiceImpl();
    private final UpdatableBCrypt bcrypt = new UpdatableBCrypt(12);
    private final MainFrame mainFrame;
    private String selectedId;
    /**
     * Creates new form ResepsionisPanel
     */
    public LaboratoriumPanel(MainFrame mainFrame) {
        initComponents();
        getTableData();
        getLabDivision();
        this.mainFrame = mainFrame;
        PasswordTitle.setVisible(false);
        PasswordInput.setVisible(false);
    }
    
    public void getTableData() {
        DefaultTableModel tm = (DefaultTableModel) TableLab.getModel();
        tm.setRowCount(0);
        try {
            List<Laboratorium> Laboratoriums = labService.findAll();
            for (Laboratorium rcp : Laboratoriums) {
                Object[] row = {
                    rcp.getId(),
                    rcp.getName(),
                    rcp.getEmail(),
                    rcp.getPhone(),
                    rcp.getDivision().getName(),
                    rcp.getCreatedAt().toString()
                };
                tm.addRow(row);
            }
        } catch (NullPointerException e) {
        }
        
    }
    
    public void resetForm() {
        NameInput.setText(null);
        EmailInput.setText(null);
        PhoneInput.setText(null);
        AddressInput.setText(null);
        PasswordCheck.setSelected(false);
        PasswordInput.setText(null);
        this.selectedId = null;
    }

    public void store() {
        Laboratorium labUser = new Laboratorium();
        labUser.setName(NameInput.getText());
        labUser.setEmail(EmailInput.getText());
        labUser.setPhone(PhoneInput.getText());
        labUser.setAddress(AddressInput.getText());
        ComboItem divisionItem = (ComboItem) SelectDivision.getSelectedItem();
        labUser.setDivisionId(divisionItem.getValue());
        if (PasswordCheck.isSelected()) {
            labUser.setPassword(bcrypt.hash(new String(PasswordInput.getPassword())));
        }
        if (selectedId != null) {
            labUser.setId(selectedId);
            labService.update(labUser);
        }else {
            labService.insert(labUser);
        }
    }
    
    public void delete() {  
        labService.delete(selectedId);
    }
    public void getLabDivision() {
        try {
            SelectDivision.removeAllItems();
            List<LaboratoriumDivision> division = labDivisionService.findAll();
            for (LaboratoriumDivision div : division) {
                SelectDivision.addItem(
                    new ComboItem(div.getName(), div.getId())
                );
            }   
        } catch (NullPointerException e) {
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnSave = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        NameInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        PhoneInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressInput = new javax.swing.JTextArea();
        PasswordCheck = new javax.swing.JCheckBox();
        PasswordTitle = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SelectDivision = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLab = new javax.swing.JTable();

        setName("admin"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nama");

        jLabel2.setText("Email");

        jLabel3.setText("No. Telepon");

        jLabel4.setText("Alamat");

        BtnSave.setText("Simpan");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnDelete.setText("Hapus");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        AddressInput.setColumns(10);
        AddressInput.setRows(3);
        jScrollPane1.setViewportView(AddressInput);

        PasswordCheck.setText("Masukan Password ?");
        PasswordCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PasswordCheckItemStateChanged(evt);
            }
        });
        PasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCheckActionPerformed(evt);
            }
        });

        PasswordTitle.setText("Password");

        jButton1.setText("Bagian Lab");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Bagian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EmailInput)
                            .addComponent(NameInput)
                            .addComponent(PhoneInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(SelectDivision, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnSave)
                        .addGap(3, 3, 3)
                        .addComponent(BtnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PasswordTitle)
                        .addGap(18, 18, 18)
                        .addComponent(PasswordInput)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTitle)
                    .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(SelectDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(BtnReset)
                    .addComponent(BtnDelete)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        TableLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama", "Email", "No. Telepon", "Bagian", "Dibuat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableLab.removeColumn(TableLab.getColumnModel().getColumn(0));
        TableLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableLabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableLab);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
        getTableData();
        getLabDivision();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void PasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordCheckActionPerformed

    private void PasswordCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PasswordCheckItemStateChanged
        // TODO add your handling code here:
        PasswordInput.setText(null);
        if (evt.getStateChange() == 1) {
            PasswordTitle.setVisible(true);
            PasswordInput.setVisible(true);
        } else {
            PasswordInput.setVisible(false);
            PasswordTitle.setVisible(false);
        }
    }//GEN-LAST:event_PasswordCheckItemStateChanged

    private void TableLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableLabMouseClicked
        // TODO add your handling code here:
        this.selectedId = TableLab.getModel().getValueAt(TableLab.getSelectedRow(), 0).toString();
        Laboratorium recep = labService.findById(selectedId);
        NameInput.setText(recep.getName());
        EmailInput.setText(recep.getEmail());
        PhoneInput.setText(recep.getPhone());
        AddressInput.setText(recep.getAddress());
        SelectDivision.getModel().setSelectedItem(new ComboItem(recep.getDivision().getName(), recep.getDivision().getId()));
    }//GEN-LAST:event_TableLabMouseClicked

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        store();
        resetForm();
        getTableData();
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showOptionDialog(
                this,
                "Anda Yakin?",
                "Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, 
                null,
                null,
                null
        );
        if (confirm == JOptionPane.YES_OPTION) {
            delete();
            resetForm();
            getTableData();
            JOptionPane.showMessageDialog(this, "Data telah dihapus.");
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainFrame.navigate("labDivision");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressInput;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSave;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JTextField NameInput;
    private javax.swing.JCheckBox PasswordCheck;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JTextField PhoneInput;
    private javax.swing.JComboBox<ComboItem> SelectDivision;
    private javax.swing.JTable TableLab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
