/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;
import com.mycompany.maven.app.model.Menu;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author mac
 */
public class MainFrame extends javax.swing.JFrame {

    private final ArrayList<Menu> menus = new ArrayList<Menu>();
    CardLayout cl = new CardLayout();
    Color menuIn = new Color(44, 61, 79);
    Color menuOut = new Color(52,73,94);
    String activedMenu = "SidebarHome";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        menus.add(new Menu("home", SidebarHome, new HomePanel()));
        menus.add(new Menu("dokter", SidebarDokter, new DokterPanel()));
        
        PasienPanel pasienPanel = new PasienPanel(MainFrame.this);
        Menu pasienMenu = new Menu("pasien", SidebarPasien, pasienPanel);
        PasienCheckup pasienCheck = new PasienCheckup(MainFrame.this, pasienPanel);
        Menu pasienCheckup = new Menu("pasienCheckup", null, pasienCheck);
        ArrayList<Menu> pasienChildren = new ArrayList();
        pasienChildren.add(pasienCheckup);
        pasienMenu.setChildren(pasienChildren);
        menus.add(pasienMenu);
        
        menus.add(new Menu("obat", SidebarObat, new ObatPanel()));
        menus.add(new Menu("kamar", SidebarKamar, new KamarPanel()));
        menus.add(new Menu("laporan", SidebarLaporan, new LaporanPanel()));
        
        // first load
        JPanel dashboardPanel = new HomePanel();
        dashboardPanel.setVisible(true);
//        Body.add(dashboardPanel, java.awt.BorderLayout.CENTER);        
        Body.setLayout(cl);
        Body.add(dashboardPanel);
        SidebarHome.setBackground(menuIn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        DashboardLabel = new javax.swing.JLabel();
        SidebarHome = new javax.swing.JPanel();
        SidebarHomeIcon = new javax.swing.JLabel();
        SidebarHomeTitle = new javax.swing.JLabel();
        SidebarDokter = new javax.swing.JPanel();
        SidebarDokterIcon = new javax.swing.JLabel();
        SidebarDokterTitle = new javax.swing.JLabel();
        SidebarPasien = new javax.swing.JPanel();
        SidebarPasienIcon = new javax.swing.JLabel();
        SidebarPasienTitle = new javax.swing.JLabel();
        SidebarObat = new javax.swing.JPanel();
        SidebarObatIcon = new javax.swing.JLabel();
        SidebarObatTitle = new javax.swing.JLabel();
        SidebarKamar = new javax.swing.JPanel();
        SidebarKamarIcon = new javax.swing.JLabel();
        SidebarKamarTitle = new javax.swing.JLabel();
        SidebarLaporan = new javax.swing.JPanel();
        SidebarLaporanIcon = new javax.swing.JLabel();
        SidebarLaporanTitle = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        HeaderBody = new javax.swing.JPanel();
        HeaderUser = new javax.swing.JLabel();
        HeaderIcon = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Klinik Erni");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        Sidebar.setBackground(new java.awt.Color(52, 73, 94));
        Sidebar.setPreferredSize(new java.awt.Dimension(160, 360));
        Sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        DashboardLabel.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        DashboardLabel.setText("Dashboard");
        DashboardLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        DashboardLabel.setPreferredSize(new java.awt.Dimension(160, 60));
        Sidebar.add(DashboardLabel);

        SidebarHome.setBackground(new java.awt.Color(52, 73, 94));
        SidebarHome.setName("SidebarHome"); // NOI18N
        SidebarHome.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarHomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarHomeMouseEntered(evt);
            }
        });
        SidebarHome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarHomeIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarHomeIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarHomeIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/home.png")); // NOI18N
        SidebarHomeIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarHomeIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarHome.add(SidebarHomeIcon);
        ImageIcon imageIcon = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/home.png"); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        SidebarHomeIcon.setIcon(imageIcon);

        SidebarHomeTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarHomeTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarHomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarHomeTitle.setText("Home");
        SidebarHome.add(SidebarHomeTitle);

        Sidebar.add(SidebarHome);

        SidebarDokter.setBackground(new java.awt.Color(52, 73, 94));
        SidebarDokter.setName("SidebarDokter"); // NOI18N
        SidebarDokter.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarDokterMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarDokterMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarDokterMouseEntered(evt);
            }
        });
        SidebarDokter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarDokterIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarDokterIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarDokterIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarDokterIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/doctor.png")); // NOI18N
        SidebarDokterIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarDokterIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarDokter.add(SidebarDokterIcon);
        ImageIcon imageIconDokter = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/doctor.png"); // load the image to a imageIcon
        Image imageDokter = imageIconDokter.getImage(); // transform it
        Image newimgDokter = imageDokter.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconDokter = new ImageIcon(newimgDokter);  // transform it back
        SidebarDokterIcon.setIcon(imageIconDokter);

        SidebarDokterTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarDokterTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarDokterTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarDokterTitle.setText("Dokter");
        SidebarDokter.add(SidebarDokterTitle);

        Sidebar.add(SidebarDokter);

        SidebarPasien.setBackground(new java.awt.Color(52, 73, 94));
        SidebarPasien.setName("SidebarPasien"); // NOI18N
        SidebarPasien.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarPasienMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarPasienMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarPasienMouseEntered(evt);
            }
        });
        SidebarPasien.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarPasienIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarPasienIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarPasienIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarPasienIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/user.png")); // NOI18N
        SidebarPasienIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarPasienIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarPasien.add(SidebarPasienIcon);
        ImageIcon imageIconPasien = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/user.png"); // load the image to a imageIcon
        Image imagePasien = imageIconPasien.getImage(); // transform it
        Image newimgPasien = imagePasien.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconPasien = new ImageIcon(newimgPasien);  // transform it back
        SidebarPasienIcon.setIcon(imageIconPasien);

        SidebarPasienTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarPasienTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarPasienTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarPasienTitle.setText("Pasien");
        SidebarPasien.add(SidebarPasienTitle);

        Sidebar.add(SidebarPasien);

        SidebarObat.setBackground(new java.awt.Color(52, 73, 94));
        SidebarObat.setName("SidebarObat"); // NOI18N
        SidebarObat.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarObatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarObatMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarObatMouseEntered(evt);
            }
        });
        SidebarObat.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarObatIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarObatIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarObatIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarObatIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/tabler-pill.png")); // NOI18N
        SidebarObatIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarObatIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarObat.add(SidebarObatIcon);
        ImageIcon imageIconObat = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/tabler-pill.png"); // load the image to a imageIcon
        Image imageObat = imageIconObat.getImage(); // transform it
        Image newimgObat = imageObat.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconObat = new ImageIcon(newimgObat);  // transform it back
        SidebarObatIcon.setIcon(imageIconObat);

        SidebarObatTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarObatTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarObatTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarObatTitle.setText("Obat");
        SidebarObat.add(SidebarObatTitle);

        Sidebar.add(SidebarObat);

        SidebarKamar.setBackground(new java.awt.Color(52, 73, 94));
        SidebarKamar.setName("SidebarKamar"); // NOI18N
        SidebarKamar.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarKamarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarKamarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarKamarMouseEntered(evt);
            }
        });
        SidebarKamar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarKamarIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarKamarIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarKamarIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarKamarIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/bed.png")); // NOI18N
        SidebarKamarIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarKamarIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarKamar.add(SidebarKamarIcon);
        ImageIcon imageIconKamar = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/bed.png"); // load the image to a imageIcon
        Image imageKamar = imageIconKamar.getImage(); // transform it
        Image newimgKamar = imageKamar.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconKamar = new ImageIcon(newimgKamar);  // transform it back
        SidebarKamarIcon.setIcon(imageIconKamar);

        SidebarKamarTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarKamarTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarKamarTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarKamarTitle.setText("Kamar");
        SidebarKamar.add(SidebarKamarTitle);

        Sidebar.add(SidebarKamar);

        SidebarLaporan.setBackground(new java.awt.Color(52, 73, 94));
        SidebarLaporan.setName("SidebarLaporan"); // NOI18N
        SidebarLaporan.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarLaporanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarLaporanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarLaporanMouseEntered(evt);
            }
        });
        SidebarLaporan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarLaporanIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarLaporanIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLaporanIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarLaporanIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/file-text.png")); // NOI18N
        SidebarLaporanIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarLaporanIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarLaporan.add(SidebarLaporanIcon);
        ImageIcon imageIconLaporan = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/file-text.png"); // load the image to a imageIcon
        Image imageLaporan = imageIconLaporan.getImage(); // transform it
        Image newimgLaporan = imageLaporan.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconLaporan = new ImageIcon(newimgLaporan);  // transform it back
        SidebarLaporanIcon.setIcon(imageIconLaporan);

        SidebarLaporanTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarLaporanTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarLaporanTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLaporanTitle.setText("Laporan");
        SidebarLaporan.add(SidebarLaporanTitle);

        Sidebar.add(SidebarLaporan);

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main.setBackground(new java.awt.Color(223, 230, 233));
        Main.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(99, 110, 114));
        Header.setPreferredSize(new java.awt.Dimension(100, 60));
        Header.setLayout(new java.awt.BorderLayout());

        HeaderBody.setBackground(new java.awt.Color(99, 110, 114));
        HeaderBody.setPreferredSize(new java.awt.Dimension(120, 60));
        HeaderBody.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 20));

        HeaderUser.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        HeaderUser.setForeground(new java.awt.Color(255, 255, 255));
        HeaderUser.setText("Admin");
        HeaderBody.add(HeaderUser);

        HeaderIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/account_circle.png")); // NOI18N
        HeaderIcon.setPreferredSize(new java.awt.Dimension(26, 26));
        HeaderBody.add(HeaderIcon);
        ImageIcon imageIconHeader = new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/maven-app/src/main/java/assets/account_circle.png"); // load the image to a imageIcon
        Image imageHeader = imageIconHeader.getImage(); // transform it
        Image newimgHeader = imageHeader.getScaledInstance(26, 26,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconHeader = new ImageIcon(newimgHeader);  // transform it back
        HeaderIcon.setIcon(imageIconHeader);

        Header.add(HeaderBody, java.awt.BorderLayout.LINE_END);

        Main.add(Header, java.awt.BorderLayout.PAGE_START);

        Body.setBackground(new java.awt.Color(223, 230, 233));
        Body.setLayout(new java.awt.BorderLayout());
        Main.add(Body, java.awt.BorderLayout.CENTER);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mouseInMenu(JPanel myPanel) {
        myPanel.setBackground(menuIn);
    }
    public void mouseOutMenu(JPanel myPanel) {
        if (myPanel.getName() != activedMenu) {
            myPanel.setBackground(menuOut);   
        }
    }
    
    public void navigate(String name) {
        cl.show(Body, name);
    }
    
    public void nestedMenu(ArrayList<Menu> menus) {   
        for (Iterator<Menu> iterator = menus.iterator(); iterator.hasNext();) {
            Menu next = iterator.next();
            Body.add(next.getMenuComponent(), next.getName());
            if (next.getChildren() != null && !next.getChildren().isEmpty()) {
                nestedMenu(next.getChildren());
            }
        } 
    }
    
    public void openMenu(javax.swing.JPanel myPanel) {
        for (Iterator<Menu> iterator = menus.iterator(); iterator.hasNext();) {
            Menu next = iterator.next();
            next.getMenu().setBackground(menuOut);
            
            if (next.getMenu().getName() == myPanel.getName()) {
                next.getMenu().setBackground(menuIn);
                activedMenu = myPanel.getName();
                Body.removeAll();
                Body.repaint();
                Body.revalidate();
                Body.add(next.getMenuComponent(), next.getName());
                if (next.getChildren() != null && !next.getChildren().isEmpty()) {                   
                    this.nestedMenu(next.getChildren());                    
                }
                Body.repaint();
                Body.revalidate();
            }
        }
        
    }
    
    private void SidebarHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHomeMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarHome);
    }//GEN-LAST:event_SidebarHomeMouseEntered

    private void SidebarHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHomeMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarHome);
    }//GEN-LAST:event_SidebarHomeMouseExited

    private void SidebarDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarDokterMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarDokter);
    }//GEN-LAST:event_SidebarDokterMouseEntered

    private void SidebarDokterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarDokterMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarDokter);
    }//GEN-LAST:event_SidebarDokterMouseExited

    private void SidebarPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPasienMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarPasien);
    }//GEN-LAST:event_SidebarPasienMouseEntered

    private void SidebarPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPasienMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarPasien);
    }//GEN-LAST:event_SidebarPasienMouseExited

    private void SidebarObatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarObatMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarObat);
    }//GEN-LAST:event_SidebarObatMouseEntered

    private void SidebarObatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarObatMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarObat);
    }//GEN-LAST:event_SidebarObatMouseExited

    private void SidebarKamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarKamarMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarKamar);
    }//GEN-LAST:event_SidebarKamarMouseEntered

    private void SidebarKamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarKamarMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarKamar);
    }//GEN-LAST:event_SidebarKamarMouseExited

    private void SidebarLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaporanMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarLaporan);
    }//GEN-LAST:event_SidebarLaporanMouseEntered

    private void SidebarLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaporanMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarLaporan);
    }//GEN-LAST:event_SidebarLaporanMouseExited

    private void SidebarHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHomeMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarHome);
    }//GEN-LAST:event_SidebarHomeMouseClicked

    private void SidebarDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarDokterMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarDokter);
    }//GEN-LAST:event_SidebarDokterMouseClicked

    private void SidebarPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPasienMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarPasien);
    }//GEN-LAST:event_SidebarPasienMouseClicked

    private void SidebarObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarObatMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarObat);
    }//GEN-LAST:event_SidebarObatMouseClicked

    private void SidebarKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarKamarMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarKamar);
    }//GEN-LAST:event_SidebarKamarMouseClicked

    private void SidebarLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaporanMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarLaporan);
    }//GEN-LAST:event_SidebarLaporanMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new MainFrame();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel DashboardLabel;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HeaderBody;
    private javax.swing.JLabel HeaderIcon;
    private javax.swing.JLabel HeaderUser;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel SidebarDokter;
    private javax.swing.JLabel SidebarDokterIcon;
    private javax.swing.JLabel SidebarDokterTitle;
    private javax.swing.JPanel SidebarHome;
    private javax.swing.JLabel SidebarHomeIcon;
    private javax.swing.JLabel SidebarHomeTitle;
    private javax.swing.JPanel SidebarKamar;
    private javax.swing.JLabel SidebarKamarIcon;
    private javax.swing.JLabel SidebarKamarTitle;
    private javax.swing.JPanel SidebarLaporan;
    private javax.swing.JLabel SidebarLaporanIcon;
    private javax.swing.JLabel SidebarLaporanTitle;
    private javax.swing.JPanel SidebarObat;
    private javax.swing.JLabel SidebarObatIcon;
    private javax.swing.JLabel SidebarObatTitle;
    private javax.swing.JPanel SidebarPasien;
    private javax.swing.JLabel SidebarPasienIcon;
    private javax.swing.JLabel SidebarPasienTitle;
    // End of variables declaration//GEN-END:variables
}
