/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;
import com.mycompany.maven.app.MainProgram;
import com.mycompany.maven.app.model.Authentication;
import com.mycompany.maven.app.model.Menu;
import com.mycompany.maven.app.service.DoctorServiceImpl;
import com.mycompany.maven.app.service.LabDivisionServiceImpl;
import com.mycompany.maven.app.service.LaboratoriumServiceImpl;
import com.mycompany.maven.app.service.MedicineServiceImpl;
import com.mycompany.maven.app.service.PatientCheckupMedicineService;
import com.mycompany.maven.app.service.PatientCheckupServiceImpl;
import com.mycompany.maven.app.service.PatientServiceImpl;
import com.mycompany.maven.app.service.SpecializeDoctorServiceImpl;
import com.mycompany.maven.app.util.UpdatableBCrypt;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author mac
 */
public class MainFrame extends javax.swing.JFrame {

    private final ArrayList<Menu> menus = new ArrayList<Menu>();
    @Setter
    @Getter
    private Authentication authentication;
    CardLayout cl = new CardLayout();
    Color MENU_IN = new Color(44, 61, 79);
    Color MENU_OUT = new Color(52,73,94);
    String activedMenu = "SidebarHome";
    
    private final DoctorServiceImpl doctorService = new DoctorServiceImpl();
    private final PatientServiceImpl patientService = new PatientServiceImpl();
    private final PatientCheckupServiceImpl patientCheckupService = new PatientCheckupServiceImpl();
    private final MedicineServiceImpl medicineService = new MedicineServiceImpl();
    private final PatientCheckupMedicineService patientCheckupMedicineService = new PatientCheckupMedicineService();
    private final SpecializeDoctorServiceImpl specializeDoctorService = new SpecializeDoctorServiceImpl();
    private final LaboratoriumServiceImpl labService = new LaboratoriumServiceImpl();
    private final LabDivisionServiceImpl labDivsionService = new LabDivisionServiceImpl();
    private final UpdatableBCrypt bcrypt = new UpdatableBCrypt(12);
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        // first load
        JPanel dashboardPanel = new HomePanel();
        dashboardPanel.setVisible(true);
//        Body.add(dashboardPanel, java.awt.BorderLayout.CENTER);        
        Body.setLayout(cl);
        Body.add(dashboardPanel);
        SidebarHome.setBackground(MENU_IN);
    }

    public MainFrame(MainProgram aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        DashboardLabel = new javax.swing.JLabel();
        SidebarHome = new javax.swing.JPanel();
        SidebarHomeIcon = new javax.swing.JLabel();
        SidebarHomeTitle = new javax.swing.JLabel();
        SidebarDokter = new javax.swing.JPanel();
        SidebarDokterIcon = new javax.swing.JLabel();
        SidebarDokterTitle = new javax.swing.JLabel();
        SidebarHasilPemeriksaan = new javax.swing.JPanel();
        SidebarHasilIcon = new javax.swing.JLabel();
        SidebarDokterTitle1 = new javax.swing.JLabel();
        SidebarResepsionis = new javax.swing.JPanel();
        SidebarResepsionislcon = new javax.swing.JLabel();
        SidebarResepsionisTitle = new javax.swing.JLabel();
        SidebarApoteker = new javax.swing.JPanel();
        SidebarApotekerlcon = new javax.swing.JLabel();
        SidebarApotekerTitle = new javax.swing.JLabel();
        SidebarAdmin = new javax.swing.JPanel();
        SidebarAdminIcon = new javax.swing.JLabel();
        SidebarAdminTitle = new javax.swing.JLabel();
        SidebarPimpinan = new javax.swing.JPanel();
        SidebarPimpinanIcon = new javax.swing.JLabel();
        SidebarPimpinanTitle = new javax.swing.JLabel();
        SidebarLaboratorium = new javax.swing.JPanel();
        SidebarLaboratoriumIcon = new javax.swing.JLabel();
        SidebarLaboratoriumTitle = new javax.swing.JLabel();
        SidebarPasien = new javax.swing.JPanel();
        SidebarPasienIcon = new javax.swing.JLabel();
        SidebarPasienTitle = new javax.swing.JLabel();
        SidebarObat = new javax.swing.JPanel();
        SidebarObatIcon = new javax.swing.JLabel();
        SidebarObatTitle = new javax.swing.JLabel();
        SidebarKamar = new javax.swing.JPanel();
        SidebarKamarIcon = new javax.swing.JLabel();
        SidebarKamarTitle = new javax.swing.JLabel();
        SidebarAntrian = new javax.swing.JPanel();
        SidebarAntrianIcon = new javax.swing.JLabel();
        SidebarAntrianTitle = new javax.swing.JLabel();
        SidebarLaporan = new javax.swing.JPanel();
        SidebarLaporanIcon = new javax.swing.JLabel();
        SidebarLaporanTitle = new javax.swing.JLabel();
        SidebarLogout = new javax.swing.JPanel();
        SidebarLogoutIcon = new javax.swing.JLabel();
        SidebarLogoutTitle = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        HeaderBody = new javax.swing.JPanel();
        HeaderUser = new javax.swing.JLabel();
        HeaderIcon = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Klinik Erni");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Sidebar.setBackground(new java.awt.Color(52, 73, 94));
        Sidebar.setPreferredSize(new java.awt.Dimension(160, 360));
        Sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        DashboardLabel.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        DashboardLabel.setText("Dashboard");
        DashboardLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        DashboardLabel.setPreferredSize(new java.awt.Dimension(160, 60));
        Sidebar.add(DashboardLabel);

        SidebarHome.setBackground(new java.awt.Color(52, 73, 94));
        SidebarHome.setName("SidebarHome"); // NOI18N
        SidebarHome.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarHomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarHomeMouseEntered(evt);
            }
        });
        SidebarHome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarHomeIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarHomeIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarHomeIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarHomeIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarHome.add(SidebarHomeIcon);
        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/assets/home.png")); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        SidebarHomeIcon.setIcon(imageIcon);

        SidebarHomeTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarHomeTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarHomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarHomeTitle.setText("Home");
        SidebarHome.add(SidebarHomeTitle);

        Sidebar.add(SidebarHome);

        SidebarDokter.setBackground(new java.awt.Color(52, 73, 94));
        SidebarDokter.setName("SidebarDokter"); // NOI18N
        SidebarDokter.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarDokterMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarDokterMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarDokterMouseEntered(evt);
            }
        });
        SidebarDokter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarDokterIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarDokterIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarDokterIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarDokterIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarDokterIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarDokter.add(SidebarDokterIcon);
        ImageIcon imageIconDokter = new javax.swing.ImageIcon(getClass().getResource("/assets/doctor.png")); // load the image to a imageIcon
        Image imageDokter = imageIconDokter.getImage(); // transform it
        Image newimgDokter = imageDokter.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconDokter = new ImageIcon(newimgDokter);  // transform it back
        SidebarDokterIcon.setIcon(imageIconDokter);

        SidebarDokterTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarDokterTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarDokterTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarDokterTitle.setText("Dokter");
        SidebarDokter.add(SidebarDokterTitle);

        Sidebar.add(SidebarDokter);

        SidebarHasilPemeriksaan.setBackground(new java.awt.Color(52, 73, 94));
        SidebarHasilPemeriksaan.setName("SidebarHasilPemeriksaan"); // NOI18N
        SidebarHasilPemeriksaan.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarHasilPemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarHasilPemeriksaanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarHasilPemeriksaanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarHasilPemeriksaanMouseEntered(evt);
            }
        });
        SidebarHasilPemeriksaan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarHasilIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarHasilIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarHasilIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarHasilIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarHasilIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarHasilPemeriksaan.add(SidebarHasilIcon);
        ImageIcon imageIconHasil = new javax.swing.ImageIcon(getClass().getResource("/assets/hasil-pemeriksaan.png")); // load the image to a imageIcon
        Image imageHasil = imageIconHasil.getImage(); // transform it
        Image newimgHasil = imageHasil.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconHasil = new ImageIcon(newimgHasil);  // transform it back
        SidebarHasilIcon.setIcon(imageIconHasil);

        SidebarDokterTitle1.setBackground(new java.awt.Color(255, 255, 255));
        SidebarDokterTitle1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarDokterTitle1.setForeground(new java.awt.Color(255, 255, 255));
        SidebarDokterTitle1.setText("Pemeriksaan");
        SidebarHasilPemeriksaan.add(SidebarDokterTitle1);

        Sidebar.add(SidebarHasilPemeriksaan);

        SidebarResepsionis.setBackground(new java.awt.Color(52, 73, 94));
        SidebarResepsionis.setName("SidebarResepsionis"); // NOI18N
        SidebarResepsionis.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarResepsionis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarResepsionisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarResepsionisMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarResepsionisMouseEntered(evt);
            }
        });
        SidebarResepsionis.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarResepsionislcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarResepsionislcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarResepsionislcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarResepsionislcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarResepsionislcon.setSize(new java.awt.Dimension(32, 32));
        SidebarResepsionis.add(SidebarResepsionislcon);
        ImageIcon imageIconResepsionis = new javax.swing.ImageIcon(getClass().getResource("/assets/resepsionis.png")); // load the image to a imageIcon
        Image imageResepsionis = imageIconResepsionis.getImage(); // transform it
        Image newimgResepsionis = imageResepsionis.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconResepsionis = new ImageIcon(newimgResepsionis);  // transform it back
        SidebarResepsionislcon.setIcon(imageIconResepsionis);

        SidebarResepsionisTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarResepsionisTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarResepsionisTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarResepsionisTitle.setText("Resepsionis");
        SidebarResepsionis.add(SidebarResepsionisTitle);

        Sidebar.add(SidebarResepsionis);

        SidebarApoteker.setBackground(new java.awt.Color(52, 73, 94));
        SidebarApoteker.setName("SidebarApoteker"); // NOI18N
        SidebarApoteker.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarApoteker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarApotekerMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarApotekerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarApotekerMouseEntered(evt);
            }
        });
        SidebarApoteker.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarApotekerlcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarApotekerlcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarApotekerlcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarApotekerlcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarApotekerlcon.setSize(new java.awt.Dimension(32, 32));
        SidebarApoteker.add(SidebarApotekerlcon);
        ImageIcon imageIconApoteker = new javax.swing.ImageIcon(getClass().getResource("/assets/apoteker.png")); // load the image to a imageIcon
        Image imageApoteker = imageIconApoteker.getImage(); // transform it
        Image newimgApoteker = imageApoteker.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconApoteker = new ImageIcon(newimgApoteker);  // transform it back
        SidebarApotekerlcon.setIcon(imageIconApoteker);

        SidebarApotekerTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarApotekerTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarApotekerTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarApotekerTitle.setText("Apoteker");
        SidebarApoteker.add(SidebarApotekerTitle);

        Sidebar.add(SidebarApoteker);

        SidebarAdmin.setBackground(new java.awt.Color(52, 73, 94));
        SidebarAdmin.setName("SidebarAdmin"); // NOI18N
        SidebarAdmin.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarAdminMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarAdminMouseEntered(evt);
            }
        });
        SidebarAdmin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarAdminIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarAdminIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarAdminIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarAdminIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarAdminIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarAdmin.add(SidebarAdminIcon);
        ImageIcon imageIconAdmin = new javax.swing.ImageIcon(getClass().getResource("/assets/user.png")); // load the image to a imageIcon
        Image imageAdmin = imageIconAdmin.getImage(); // transform it
        Image newimgAdmin = imageAdmin.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconAdmin = new ImageIcon(newimgAdmin);  // transform it back
        SidebarAdminIcon.setIcon(imageIconAdmin);

        SidebarAdminTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarAdminTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarAdminTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarAdminTitle.setText("Admin");
        SidebarAdmin.add(SidebarAdminTitle);

        Sidebar.add(SidebarAdmin);

        SidebarPimpinan.setBackground(new java.awt.Color(52, 73, 94));
        SidebarPimpinan.setName("SidebarPimpinan"); // NOI18N
        SidebarPimpinan.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarPimpinan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarPimpinanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarPimpinanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarPimpinanMouseEntered(evt);
            }
        });
        SidebarPimpinan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarPimpinanIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarPimpinanIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarPimpinanIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarPimpinanIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarPimpinanIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarPimpinan.add(SidebarPimpinanIcon);
        ImageIcon imageIconPimpinan = new javax.swing.ImageIcon(getClass().getResource("/assets/pimpinan.png")); // load the image to a imageIcon
        Image imagePimpinan = imageIconPimpinan.getImage(); // transform it
        Image newimgPimpinan = imagePimpinan.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconPimpinan = new ImageIcon(newimgPimpinan);  // transform it back
        SidebarPimpinanIcon.setIcon(imageIconPimpinan);

        SidebarPimpinanTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarPimpinanTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarPimpinanTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarPimpinanTitle.setText("Pimpinan");
        SidebarPimpinan.add(SidebarPimpinanTitle);

        Sidebar.add(SidebarPimpinan);

        SidebarLaboratorium.setBackground(new java.awt.Color(52, 73, 94));
        SidebarLaboratorium.setName("SidebarLaboratorium"); // NOI18N
        SidebarLaboratorium.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarLaboratorium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarLaboratoriumMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarLaboratoriumMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarLaboratoriumMouseEntered(evt);
            }
        });
        SidebarLaboratorium.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarLaboratoriumIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarLaboratoriumIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLaboratoriumIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarLaboratoriumIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarLaboratoriumIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarLaboratorium.add(SidebarLaboratoriumIcon);
        ImageIcon imageIconLab = new javax.swing.ImageIcon(getClass().getResource("/assets/pimpinan.png")); // load the image to a imageIcon
        Image imageLab = imageIconLab.getImage(); // transform it
        Image newimgLab = imageLab.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconLab = new ImageIcon(newimgLab);  // transform it back
        SidebarLaboratoriumIcon.setIcon(imageIconLab);

        SidebarLaboratoriumTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarLaboratoriumTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarLaboratoriumTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLaboratoriumTitle.setText("Laboratorium");
        SidebarLaboratorium.add(SidebarLaboratoriumTitle);

        Sidebar.add(SidebarLaboratorium);

        SidebarPasien.setBackground(new java.awt.Color(52, 73, 94));
        SidebarPasien.setName("SidebarPasien"); // NOI18N
        SidebarPasien.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarPasienMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarPasienMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarPasienMouseEntered(evt);
            }
        });
        SidebarPasien.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarPasienIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarPasienIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarPasienIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarPasienIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarPasienIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarPasien.add(SidebarPasienIcon);
        ImageIcon imageIconPasien = new javax.swing.ImageIcon(getClass().getResource("/assets/user.png")); // load the image to a imageIcon
        Image imagePasien = imageIconPasien.getImage(); // transform it
        Image newimgPasien = imagePasien.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconPasien = new ImageIcon(newimgPasien);  // transform it back
        SidebarPasienIcon.setIcon(imageIconPasien);

        SidebarPasienTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarPasienTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarPasienTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarPasienTitle.setText("Pasien");
        SidebarPasien.add(SidebarPasienTitle);

        Sidebar.add(SidebarPasien);

        SidebarObat.setBackground(new java.awt.Color(52, 73, 94));
        SidebarObat.setName("SidebarObat"); // NOI18N
        SidebarObat.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarObatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarObatMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarObatMouseEntered(evt);
            }
        });
        SidebarObat.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarObatIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarObatIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarObatIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarObatIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarObatIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarObat.add(SidebarObatIcon);
        ImageIcon imageIconObat = new javax.swing.ImageIcon(getClass().getResource("/assets/tabler-pill.png")); // load the image to a imageIcon
        Image imageObat = imageIconObat.getImage(); // transform it
        Image newimgObat = imageObat.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconObat = new ImageIcon(newimgObat);  // transform it back
        SidebarObatIcon.setIcon(imageIconObat);

        SidebarObatTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarObatTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarObatTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarObatTitle.setText("Obat");
        SidebarObat.add(SidebarObatTitle);

        Sidebar.add(SidebarObat);

        SidebarKamar.setBackground(new java.awt.Color(52, 73, 94));
        SidebarKamar.setName("SidebarKamar"); // NOI18N
        SidebarKamar.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarKamarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarKamarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarKamarMouseEntered(evt);
            }
        });
        SidebarKamar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarKamarIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarKamarIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarKamarIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarKamarIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarKamarIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarKamar.add(SidebarKamarIcon);
        ImageIcon imageIconKamar = new javax.swing.ImageIcon(getClass().getResource("/assets/bed.png")); // load the image to a imageIcon
        Image imageKamar = imageIconKamar.getImage(); // transform it
        Image newimgKamar = imageKamar.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconKamar = new ImageIcon(newimgKamar);  // transform it back
        SidebarKamarIcon.setIcon(imageIconKamar);

        SidebarKamarTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarKamarTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarKamarTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarKamarTitle.setText("Kamar");
        SidebarKamar.add(SidebarKamarTitle);

        Sidebar.add(SidebarKamar);
        SidebarKamar.setVisible(false);

        SidebarAntrian.setBackground(new java.awt.Color(52, 73, 94));
        SidebarAntrian.setName("SidebarAntrian"); // NOI18N
        SidebarAntrian.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarAntrianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarAntrianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarAntrianMouseExited(evt);
            }
        });
        SidebarAntrian.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarAntrianIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarAntrianIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarAntrianIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarAntrianIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarAntrianIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarAntrian.add(SidebarAntrianIcon);
        ImageIcon imageIconAntrian = new javax.swing.ImageIcon(getClass().getResource("/assets/antrian.png")); // load the image to a imageIcon
        Image imageAntrian = imageIconAntrian.getImage(); // transform it
        Image newimgAntrian = imageAntrian.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconAntrian = new ImageIcon(newimgAntrian);  // transform it back
        SidebarAntrianIcon.setIcon(imageIconAntrian);

        SidebarAntrianTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarAntrianTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarAntrianTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarAntrianTitle.setText("Antrian");
        SidebarAntrian.add(SidebarAntrianTitle);

        Sidebar.add(SidebarAntrian);

        SidebarLaporan.setBackground(new java.awt.Color(52, 73, 94));
        SidebarLaporan.setName("SidebarLaporan"); // NOI18N
        SidebarLaporan.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarLaporanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarLaporanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarLaporanMouseEntered(evt);
            }
        });
        SidebarLaporan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarLaporanIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarLaporanIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLaporanIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarLaporanIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarLaporanIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarLaporan.add(SidebarLaporanIcon);
        ImageIcon imageIconLaporan = new javax.swing.ImageIcon(getClass().getResource("/assets/file-text.png")); // load the image to a imageIcon
        Image imageLaporan = imageIconLaporan.getImage(); // transform it
        Image newimgLaporan = imageLaporan.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconLaporan = new ImageIcon(newimgLaporan);  // transform it back
        SidebarLaporanIcon.setIcon(imageIconLaporan);

        SidebarLaporanTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarLaporanTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarLaporanTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLaporanTitle.setText("Laporan");
        SidebarLaporanTitle.setName("SidebarLaporan"); // NOI18N
        SidebarLaporan.add(SidebarLaporanTitle);

        Sidebar.add(SidebarLaporan);

        SidebarLogout.setBackground(new java.awt.Color(52, 73, 94));
        SidebarLogout.setName("SidebarLaporan"); // NOI18N
        SidebarLogout.setPreferredSize(new java.awt.Dimension(160, 40));
        SidebarLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SidebarLogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SidebarLogoutMouseEntered(evt);
            }
        });
        SidebarLogout.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        SidebarLogoutIcon.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        SidebarLogoutIcon.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLogoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SidebarLogoutIcon.setPreferredSize(new java.awt.Dimension(22, 22));
        SidebarLogoutIcon.setSize(new java.awt.Dimension(32, 32));
        SidebarLogout.add(SidebarLogoutIcon);
        ImageIcon imageIconLogout = new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png")); // load the image to a imageIcon
        Image imageLogout = imageIconLogout.getImage(); // transform it
        Image newimgLogout = imageLogout.getScaledInstance(22, 22,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconLogout = new ImageIcon(newimgLogout);  // transform it back
        SidebarLogoutIcon.setIcon(imageIconLogout);

        SidebarLogoutTitle.setBackground(new java.awt.Color(255, 255, 255));
        SidebarLogoutTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        SidebarLogoutTitle.setForeground(new java.awt.Color(255, 255, 255));
        SidebarLogoutTitle.setText("Logout");
        SidebarLogoutTitle.setName("SidebarLaporan"); // NOI18N
        SidebarLogout.add(SidebarLogoutTitle);

        Sidebar.add(SidebarLogout);

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Main.setBackground(new java.awt.Color(223, 230, 233));
        Main.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(99, 110, 114));
        Header.setPreferredSize(new java.awt.Dimension(100, 60));
        Header.setLayout(new java.awt.BorderLayout());

        HeaderBody.setBackground(new java.awt.Color(99, 110, 114));
        HeaderBody.setPreferredSize(new java.awt.Dimension(120, 60));
        HeaderBody.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 20));

        HeaderUser.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        HeaderUser.setForeground(new java.awt.Color(255, 255, 255));
        HeaderUser.setText("Admin");
        HeaderBody.add(HeaderUser);

        HeaderIcon.setPreferredSize(new java.awt.Dimension(26, 26));
        HeaderBody.add(HeaderIcon);
        ImageIcon imageIconHeader = new javax.swing.ImageIcon(getClass().getResource("/assets/account_circle.png")); // load the image to a imageIcon
        Image imageHeader = imageIconHeader.getImage(); // transform it
        Image newimgHeader = imageHeader.getScaledInstance(26, 26,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconHeader = new ImageIcon(newimgHeader);  // transform it back
        HeaderIcon.setIcon(imageIconHeader);

        Header.add(HeaderBody, java.awt.BorderLayout.LINE_END);

        Main.add(Header, java.awt.BorderLayout.PAGE_START);

        Body.setBackground(new java.awt.Color(223, 230, 233));
        Body.setLayout(new java.awt.BorderLayout());
        Main.add(Body, java.awt.BorderLayout.CENTER);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mouseInMenu(JPanel myPanel) {
        myPanel.setBackground(MENU_IN);
    }
    public void mouseOutMenu(JPanel myPanel) {
        if (myPanel.getName() != activedMenu) {
            myPanel.setBackground(MENU_OUT);   
        }
    }
    
    public void navigate(String name) {
        cl.show(Body, name);
    }
    
    public void nestedMenu(ArrayList<Menu> menus) {   
        for (Iterator<Menu> iterator = menus.iterator(); iterator.hasNext();) {
            Menu next = iterator.next();
            Body.add(next.getMenuComponent(), next.getName());
            if (next.getChildren() != null && !next.getChildren().isEmpty()) {
                nestedMenu(next.getChildren());
            }
        } 
    }
    
    public void openMenu(javax.swing.JPanel myPanel) {
        for (Iterator<Menu> iterator = menus.iterator(); iterator.hasNext();) {
            Menu next = iterator.next();
            next.getMenu().setBackground(MENU_OUT);
            
            if (next.getMenu().getName() == myPanel.getName()) {
                next.getMenu().setBackground(MENU_IN);
                activedMenu = myPanel.getName();
                Body.removeAll();
                Body.repaint();
                Body.revalidate();
                Body.add(next.getMenuComponent(), next.getName());
                if (next.getChildren() != null && !next.getChildren().isEmpty()) {                   
                    this.nestedMenu(next.getChildren());                    
                }
                Body.repaint();
                Body.revalidate();
            }
        }
        
    }
    
    private void SidebarHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHomeMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarHome);
    }//GEN-LAST:event_SidebarHomeMouseEntered

    private void SidebarHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHomeMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarHome);
    }//GEN-LAST:event_SidebarHomeMouseExited

    private void SidebarDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarDokterMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarDokter);
    }//GEN-LAST:event_SidebarDokterMouseEntered

    private void SidebarDokterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarDokterMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarDokter);
    }//GEN-LAST:event_SidebarDokterMouseExited

    private void SidebarPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPasienMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarPasien);
    }//GEN-LAST:event_SidebarPasienMouseEntered

    private void SidebarPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPasienMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarPasien);
    }//GEN-LAST:event_SidebarPasienMouseExited

    private void SidebarObatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarObatMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarObat);
    }//GEN-LAST:event_SidebarObatMouseEntered

    private void SidebarObatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarObatMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarObat);
    }//GEN-LAST:event_SidebarObatMouseExited

    private void SidebarKamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarKamarMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarKamar);
    }//GEN-LAST:event_SidebarKamarMouseEntered

    private void SidebarKamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarKamarMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarKamar);
    }//GEN-LAST:event_SidebarKamarMouseExited

    private void SidebarLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaporanMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarLaporan);
    }//GEN-LAST:event_SidebarLaporanMouseEntered

    private void SidebarLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaporanMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarLaporan);
    }//GEN-LAST:event_SidebarLaporanMouseExited

    private void SidebarHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHomeMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarHome);
    }//GEN-LAST:event_SidebarHomeMouseClicked

    private void SidebarDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarDokterMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarDokter);
    }//GEN-LAST:event_SidebarDokterMouseClicked

    private void SidebarPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPasienMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarPasien);
    }//GEN-LAST:event_SidebarPasienMouseClicked

    private void SidebarObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarObatMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarObat);
    }//GEN-LAST:event_SidebarObatMouseClicked

    private void SidebarKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarKamarMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarKamar);
    }//GEN-LAST:event_SidebarKamarMouseClicked

    private void SidebarLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaporanMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarLaporan);
    }//GEN-LAST:event_SidebarLaporanMouseClicked

    private void SidebarAntrianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarAntrianMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarAntrian);
    }//GEN-LAST:event_SidebarAntrianMouseClicked

    private void SidebarAntrianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarAntrianMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarAntrian);
    }//GEN-LAST:event_SidebarAntrianMouseExited

    private void SidebarAntrianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarAntrianMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarAntrian);
    }//GEN-LAST:event_SidebarAntrianMouseEntered

    private void SidebarHasilPemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHasilPemeriksaanMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarHasilPemeriksaan);
    }//GEN-LAST:event_SidebarHasilPemeriksaanMouseClicked

    private void SidebarHasilPemeriksaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHasilPemeriksaanMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarHasilPemeriksaan);
    }//GEN-LAST:event_SidebarHasilPemeriksaanMouseExited

    private void SidebarHasilPemeriksaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarHasilPemeriksaanMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarHasilPemeriksaan);
    }//GEN-LAST:event_SidebarHasilPemeriksaanMouseEntered

    private void SidebarResepsionisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarResepsionisMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarResepsionis);
    }//GEN-LAST:event_SidebarResepsionisMouseClicked

    private void SidebarResepsionisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarResepsionisMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarResepsionis);
    }//GEN-LAST:event_SidebarResepsionisMouseExited

    private void SidebarResepsionisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarResepsionisMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarResepsionis);
    }//GEN-LAST:event_SidebarResepsionisMouseEntered

    private void SidebarApotekerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarApotekerMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarApoteker);
    }//GEN-LAST:event_SidebarApotekerMouseClicked

    private void SidebarApotekerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarApotekerMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarApoteker);
    }//GEN-LAST:event_SidebarApotekerMouseExited

    private void SidebarApotekerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarApotekerMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarApoteker);
    }//GEN-LAST:event_SidebarApotekerMouseEntered

    private void SidebarPimpinanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPimpinanMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarPimpinan);
    }//GEN-LAST:event_SidebarPimpinanMouseClicked

    private void SidebarPimpinanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPimpinanMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarPimpinan);
    }//GEN-LAST:event_SidebarPimpinanMouseExited

    private void SidebarPimpinanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarPimpinanMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarPimpinan);
    }//GEN-LAST:event_SidebarPimpinanMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        menus.add(new Menu("home", SidebarHome, new HomePanel()));

        Menu doctorMenu = new Menu("dokter", SidebarDokter, new DokterPanel(bcrypt, doctorService, this, specializeDoctorService));
        SpecializeDoctorPanel specializeDoctorPanel = new SpecializeDoctorPanel(this, specializeDoctorService);
        Menu specializePanel = new Menu("specializeDoctor", null, specializeDoctorPanel);
        ArrayList<Menu> doctorChildren = new ArrayList();
        doctorChildren.add(specializePanel);
        doctorMenu.setChildren(doctorChildren);
        menus.add(doctorMenu);
        
        PasienPanel pasienPanel = new PasienPanel(this, patientService);
        Menu pasienMenu = new Menu("pasien", SidebarPasien, pasienPanel);
        PasienCheckupDoctorPanel pasienCheck = new PasienCheckupDoctorPanel(this, pasienPanel, patientCheckupService, doctorService, patientService);
        Menu pasienCheckup = new Menu("pasienCheckup", null, pasienCheck);
        ArrayList<Menu> pasienChildren = new ArrayList();
        pasienChildren.add(pasienCheckup);
        pasienMenu.setChildren(pasienChildren);
        menus.add(pasienMenu);
        
        PemeriksaanPanel pemeriksaanPanel = new PemeriksaanPanel(
                            this,
                            patientCheckupService,
                            patientService,
                            doctorService,
                            medicineService,
                            patientCheckupMedicineService
                        );
        Menu pemeriksaanMenu = new Menu(
                        "hasilPemeriksaan", 
                        SidebarHasilPemeriksaan, 
                        pemeriksaanPanel);
        ArrayList<Menu> pemeriksaanChildren = new ArrayList();
        pemeriksaanChildren.add(new Menu("pemeriksaanDetail", null, new PasienCheckupDetailPanel(this, pemeriksaanPanel, authentication)));
        pemeriksaanMenu.setChildren(pemeriksaanChildren);
        menus.add(pemeriksaanMenu);
        
        menus.add(new Menu("obat", SidebarObat, new ObatPanel()));
        menus.add(new Menu("kamar", SidebarKamar, new KamarPanel()));
        menus.add(new Menu("antrian", SidebarAntrian, new AntrianPanel()));
        menus.add(new Menu("laporan", SidebarLaporan, new LaporanPanel()));
        menus.add(new Menu("resepsionis", SidebarResepsionis, new ResepsionisPanel()));
        menus.add(new Menu("apoteker", SidebarApoteker, new ApotekerPanel()));
        menus.add(new Menu("pimpinan", SidebarPimpinan, new PimpinanPanel()));
        menus.add(new Menu("admin", SidebarAdmin, new AdminPanel()));
        
        Menu labMenu = new Menu("laboratorium", SidebarLaboratorium, new LaboratoriumPanel(this));
        LabBagianPanel bagianPanel = new LabBagianPanel(this, labDivsionService);
        ArrayList<Menu> labChildren = new ArrayList();
        labChildren.add(new Menu("labDivision", null, bagianPanel));
        labMenu.setChildren(labChildren);
        menus.add(labMenu);
        
        
        HeaderUser.setText(authentication.getName());
    }//GEN-LAST:event_formWindowOpened

    private void SidebarLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showOptionDialog(
                this,
                "Anda Yakin keluar?",
                "Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, 
                null,
                null,
                null
        );
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_SidebarLogoutMouseClicked

    private void SidebarLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLogoutMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarLogout);
    }//GEN-LAST:event_SidebarLogoutMouseExited

    private void SidebarLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLogoutMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarLogout);
    }//GEN-LAST:event_SidebarLogoutMouseEntered

    private void SidebarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarAdminMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarAdmin);
    }//GEN-LAST:event_SidebarAdminMouseClicked

    private void SidebarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarAdminMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarAdmin);
    }//GEN-LAST:event_SidebarAdminMouseExited

    private void SidebarAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarAdminMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarAdmin);
    }//GEN-LAST:event_SidebarAdminMouseEntered

    private void SidebarLaboratoriumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaboratoriumMouseClicked
        // TODO add your handling code here:
        openMenu(SidebarLaboratorium);
    }//GEN-LAST:event_SidebarLaboratoriumMouseClicked

    private void SidebarLaboratoriumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaboratoriumMouseExited
        // TODO add your handling code here:
        mouseOutMenu(SidebarLaboratorium);
    }//GEN-LAST:event_SidebarLaboratoriumMouseExited

    private void SidebarLaboratoriumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarLaboratoriumMouseEntered
        // TODO add your handling code here:
        mouseInMenu(SidebarLaboratorium);
    }//GEN-LAST:event_SidebarLaboratoriumMouseEntered
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel DashboardLabel;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HeaderBody;
    private javax.swing.JLabel HeaderIcon;
    private javax.swing.JLabel HeaderUser;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel SidebarAdmin;
    private javax.swing.JLabel SidebarAdminIcon;
    private javax.swing.JLabel SidebarAdminTitle;
    private javax.swing.JPanel SidebarAntrian;
    private javax.swing.JLabel SidebarAntrianIcon;
    private javax.swing.JLabel SidebarAntrianTitle;
    private javax.swing.JPanel SidebarApoteker;
    private javax.swing.JLabel SidebarApotekerTitle;
    private javax.swing.JLabel SidebarApotekerlcon;
    private javax.swing.JPanel SidebarDokter;
    private javax.swing.JLabel SidebarDokterIcon;
    private javax.swing.JLabel SidebarDokterTitle;
    private javax.swing.JLabel SidebarDokterTitle1;
    private javax.swing.JLabel SidebarHasilIcon;
    private javax.swing.JPanel SidebarHasilPemeriksaan;
    private javax.swing.JPanel SidebarHome;
    private javax.swing.JLabel SidebarHomeIcon;
    private javax.swing.JLabel SidebarHomeTitle;
    private javax.swing.JPanel SidebarKamar;
    private javax.swing.JLabel SidebarKamarIcon;
    private javax.swing.JLabel SidebarKamarTitle;
    private javax.swing.JPanel SidebarLaboratorium;
    private javax.swing.JLabel SidebarLaboratoriumIcon;
    private javax.swing.JLabel SidebarLaboratoriumTitle;
    private javax.swing.JPanel SidebarLaporan;
    private javax.swing.JLabel SidebarLaporanIcon;
    private javax.swing.JLabel SidebarLaporanTitle;
    private javax.swing.JPanel SidebarLogout;
    private javax.swing.JLabel SidebarLogoutIcon;
    private javax.swing.JLabel SidebarLogoutTitle;
    private javax.swing.JPanel SidebarObat;
    private javax.swing.JLabel SidebarObatIcon;
    private javax.swing.JLabel SidebarObatTitle;
    private javax.swing.JPanel SidebarPasien;
    private javax.swing.JLabel SidebarPasienIcon;
    private javax.swing.JLabel SidebarPasienTitle;
    private javax.swing.JPanel SidebarPimpinan;
    private javax.swing.JLabel SidebarPimpinanIcon;
    private javax.swing.JLabel SidebarPimpinanTitle;
    private javax.swing.JPanel SidebarResepsionis;
    private javax.swing.JLabel SidebarResepsionisTitle;
    private javax.swing.JLabel SidebarResepsionislcon;
    // End of variables declaration//GEN-END:variables
}
