/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;
import com.mycompany.maven.app.enumeration.MedicineType;
import com.mycompany.maven.app.enumeration.MedicineUse;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.maven.app.Koneksi;
import com.mycompany.maven.app.model.Medicine;
import com.mycompany.maven.app.service.MedicineServiceImpl;
import com.mycompany.maven.app.util.MedicineUtil;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.HibernateException;

/**
 *
 * @author mac
 */
public final class ObatPanel extends javax.swing.JPanel {
    private final Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    private MedicineServiceImpl medicineService;
    private String selectedId;
    private MainFrame mainFrame;

    /**
     * Creates new form ObatPanel
     */
    public ObatPanel(MainFrame mainFrame) {
        this.medicineService = new MedicineServiceImpl();
        initComponents();
        datatable();
        tabelobat.removeColumn(tabelobat.getColumnModel().getColumn(0));
        this.mainFrame = mainFrame;
    }
    protected void aktif(){
        tnama.setEnabled(true);
        tstok.setEnabled(true);
        tharga.setEnabled(true);        
    }
    protected void kosong(){
        this.selectedId = null;
        tnama.setText("");
        cap.setSelectedIndex(0);
        cjo.setSelectedIndex(0);
        tstok.setText("");
        tharga.setText("");
    }
    protected void datatable(){
        DefaultTableModel tm = (DefaultTableModel) tabelobat.getModel();
        tm.setRowCount(0);
        try {
            List<Medicine> medicines = medicineService.findAll();
            for (Medicine medicine : medicines) {
                Object[] newRow = {
                    medicine.getId(),
                    medicine.getName(),
                    MedicineUtil.medicineUseToString(medicine.getUse()),
                    medicine.getType(),
                    medicine.getStock(),
                    medicine.getPrice()
                };
                tm.addRow(newRow);
            }
        } catch (HibernateException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        North = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tstok = new javax.swing.JTextField();
        tharga = new javax.swing.JTextField();
        cap = new javax.swing.JComboBox<>();
        cjo = new javax.swing.JComboBox<>();
        East = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        South = new javax.swing.JPanel();
        Bottom = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();

        jButton4.setText("jButton4");

        setLayout(new java.awt.BorderLayout());

        North.setBackground(new java.awt.Color(223, 230, 233));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Obat");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Jenis Obat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Aturan Pakai");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Stok Obat");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Harga Obat");

        cap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x3", "1x2", "2x1" }));

        cjo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cjo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pill", "Sirup", "Salep" }));

        East.setBackground(new java.awt.Color(223, 230, 233));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrint.setText("Cetak");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EastLayout = new javax.swing.GroupLayout(East);
        East.setLayout(EastLayout);
        EastLayout.setHorizontalGroup(
            EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        EastLayout.setVerticalGroup(
            EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EastLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrint)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NorthLayout = new javax.swing.GroupLayout(North);
        North.setLayout(NorthLayout);
        NorthLayout.setHorizontalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cjo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tstok, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(tnama)
                    .addComponent(tharga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        NorthLayout.setVerticalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NorthLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cjo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tstok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap())
        );

        add(North, java.awt.BorderLayout.NORTH);

        South.setLayout(new java.awt.BorderLayout());

        Bottom.setBackground(new java.awt.Color(223, 230, 233));
        Bottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BottomMouseClicked(evt);
            }
        });

        tabelobat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama Obat", "Aturan Pakai", "Jenis Obat", "Stok Obat", "Harga Obat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelobatMouseClicked(evt);
            }
        });
        Bottom.setViewportView(tabelobat);

        South.add(Bottom, java.awt.BorderLayout.CENTER);

        add(South, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Medicine medicine = new Medicine();
        medicine.setName(tnama.getText());
        if (cap.getSelectedItem().toString() == "1x3") {
            medicine.setUse(MedicineUse.ONE_TIME_THREE);
        } else if (cap.getSelectedItem().toString() == "1x2") {
            medicine.setUse(MedicineUse.ONE_TIME_TWO);
        } else if (cap.getSelectedItem().toString() == "2x1") {
            medicine.setUse(MedicineUse.TWO_TIME_ONE);
        }

        MedicineType typeEnum = MedicineType.valueOf(cjo.getSelectedItem().toString());
        medicine.setType(typeEnum);
        medicine.setStock(Integer.parseInt(tstok.getText()));
        medicine.setPrice(Double.parseDouble(tharga.getText()));
        medicineService.insert(medicine);
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        kosong();
        datatable();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        Medicine medicine = new Medicine();
        medicine.setId(selectedId);
        medicine.setName(tnama.getText());
        if (cap.getSelectedItem().toString() == "1x3") {
            medicine.setUse(MedicineUse.ONE_TIME_THREE);
        } else if (cap.getSelectedItem().toString() == "1x2") {
            medicine.setUse(MedicineUse.ONE_TIME_TWO);
        } else if (cap.getSelectedItem().toString() == "2x1") {
            medicine.setUse(MedicineUse.TWO_TIME_ONE);
        }

        MedicineType typeEnum = MedicineType.valueOf(cjo.getSelectedItem().toString());
        medicine.setType(typeEnum);
        medicine.setStock(Integer.parseInt(tstok.getText()));
        medicine.setPrice(Double.parseDouble(tharga.getText()));
        medicineService.update(medicine);
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        kosong();
        datatable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0){
            medicineService.delete(selectedId);
            kosong();
            datatable();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        String filename = System.getProperty("user.dir") + File.separator + 
                "src" + File.separator + "main" + File.separator + "java" +
                File.separator + "com" + File.separator + "mycompany" + File.separator +
                "maven" + File.separator + "app" + File.separator + "report" + File.separator +
                "report-medicine.jrxml";
        Map<String, Object> kode = new HashMap<String, Object>();
        kode.put("username", mainFrame.getAuthentication().getName());
        kode.put("role", mainFrame.getAuthentication().getRoleText());
        kode.put(JRParameter.REPORT_LOCALE, new Locale( "id", "ID" ));
        File report = new File(filename);
        try {
            Koneksi conn = new Koneksi();
            JasperDesign jasDes = JRXmlLoader.load(report);
            JasperReport jasRep = JasperCompileManager.compileReport(jasDes);
            JasperPrint jasPri = JasperFillManager.fillReport(jasRep, kode, conn.connect());
            JasperViewer.viewReport(jasPri, false);

        } catch (Exception e) {
            System.out.println("err: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void BottomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BottomMouseClicked

    private void tabelobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelobatMouseClicked
        // TODO add your handling code here:
        Object id = tabelobat.getModel().getValueAt(tabelobat.getSelectedRow(), 0);
        this.selectedId = id.toString();
        tnama.setText(
            tabelobat.getModel().getValueAt(tabelobat.getSelectedRow(), 1).toString()
        );
        tstok.setText(
            tabelobat.getModel().getValueAt(tabelobat.getSelectedRow(), 4).toString()
        );
        tharga.setText(
            tabelobat.getModel().getValueAt(tabelobat.getSelectedRow(), 5).toString()
        );
        cap.setSelectedItem(
            tabelobat.getModel().getValueAt(tabelobat.getSelectedRow(), 2).toString()
        );
        cjo.setSelectedItem(
            tabelobat.getModel().getValueAt(tabelobat.getSelectedRow(), 3).toString()
        );
    }//GEN-LAST:event_tabelobatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Bottom;
    private javax.swing.JPanel East;
    private javax.swing.JPanel North;
    private javax.swing.JPanel South;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cap;
    private javax.swing.JComboBox<String> cjo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTable tabelobat;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tstok;
    // End of variables declaration//GEN-END:variables
}
