/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;

//import com.mycompany.maven.app.controller.ManagePatient;
//import com.mycompany.maven.app.controller.ManagePatientCheckup;
import com.mycompany.maven.app.model.Doctor;
import com.mycompany.maven.app.model.Patient;
import com.mycompany.maven.app.model.PatientCheckup;
import com.mycompany.maven.app.service.DoctorServiceImpl;
import com.mycompany.maven.app.service.PatientCheckupServiceImpl;
import com.mycompany.maven.app.service.PatientServiceImpl;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.Iterator;
import com.mycompany.maven.app.util.ComboItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import com.mycompany.maven.app.util.NumberRenderer;
/**
 *
 * @author mac
 */
public class PasienCheckupDoctorPanel extends javax.swing.JPanel {
    private final PasienPanel pasienPanel;
    private final PatientCheckupServiceImpl patientCheckupService;
    private final DoctorServiceImpl doctorService;
    private final PatientServiceImpl patientService;
    private final MainFrame mainFrame;
    private Patient patientDetail;
    private String editedId = "";
    private String patientId = "";
    /**
     * Creates new form PasienCheckup
     */
    public PasienCheckupDoctorPanel(
            MainFrame frame,
            PasienPanel pp,
            PatientCheckupServiceImpl patientCheckupService,
            DoctorServiceImpl doctorService,
            PatientServiceImpl patientService
    ) {
        initComponents();
        this.patientCheckupService = patientCheckupService;
        this.doctorService = doctorService;
        this.patientService = patientService;
        this.mainFrame = frame;
        this.pasienPanel = pp;
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
            }
            @Override
            public void componentShown(ComponentEvent evt) {
                getDataTable();
                getDoctor();
                setPatientId();
                setPatientDetail();
                setPatientNameLabel();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PatientNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        Form = new javax.swing.JPanel();
        Group = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Action = new javax.swing.JPanel();
        ResetForm = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Header.setPreferredSize(new java.awt.Dimension(602, 60));
        Header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Pemeriksaan");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Header.add(jLabel1);

        jLabel2.setText("/");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Header.add(jLabel2);
        Header.add(PatientNameLabel);

        jLabel3.setText("/");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Header.add(jLabel3);

        jLabel4.setText("Riwayat");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        Header.add(jLabel4);

        add(Header, java.awt.BorderLayout.NORTH);

        Body.setLayout(new java.awt.BorderLayout());

        Form.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Catatan Dokter");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel6.setText("Dokter");

        jLabel7.setText("-");

        javax.swing.GroupLayout GroupLayout = new javax.swing.GroupLayout(Group);
        Group.setLayout(GroupLayout);
        GroupLayout.setHorizontalGroup(
            GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        GroupLayout.setVerticalGroup(
            GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GroupLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16))
        );

        Form.add(Group, java.awt.BorderLayout.CENTER);

        Action.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        ResetForm.setText("Batal");
        ResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetFormActionPerformed(evt);
            }
        });
        Action.add(ResetForm);

        SaveButton.setText("Simpan");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        Action.add(SaveButton);

        Form.add(Action, java.awt.BorderLayout.SOUTH);

        Body.add(Form, java.awt.BorderLayout.PAGE_START);

        add(Body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void setPatientId() {
        this.patientId = pasienPanel.getEditedId();
    }
    
    public void setPatientDetail() {
        this.patientDetail = patientService.findById(patientId);
    }
    
    public void setPatientNameLabel() {
        this.PatientNameLabel.setText(patientDetail.getName());
    }
    
    public void getDoctor() {
//        for (Doctor next : this.doctorService.findAll()) {
//            SelectDoctor.addItem(new ComboItem(next.getName(), next.getId()));
//        }
    }
    public void getDataTable() {
//        DefaultTableModel tm = (DefaultTableModel) TableCheckups.getModel();
//        tm.setRowCount(0);
//        try {
//            for (Iterator<PatientCheckup> iterator = this.patientCheckupService.getAllPatientCheckupPatientId(pasienPanel.getEditedId()).iterator(); iterator.hasNext();) {
//                PatientCheckup next = (PatientCheckup) iterator.next();
//                Object[] newRow = {
//                    next.getId(),
//                    next.getDoctor().getId(),
//                    next.getDoctor().getName(),
//                    null,
//                    null,
////                    next.getPainComplaint(),
////                    next.getDiagnose(),
//                    next.getCost(),
//                    next.getCreatedAt()
//                };
//                tm.addRow(newRow);
//            }
//        } catch (HibernateException e) {
//            System.err.println("Error: " + e.getMessage());
//        }
    }
    public void refreshTable() {
//        DefaultTableModel tm = (DefaultTableModel) TableCheckups.getModel();
//        getDataTable();
//        tm.fireTableDataChanged();
//        TableCheckups.repaint();
    }
    
    public void resetForm() {
//        this.Remove.setVisible(false);
        this.editedId = "";
//        SelectDoctor.setSelectedIndex(0);;
//        ComplaintField.setText("");
//        DiagnoseField.setText("");
//        CostField.setText("");
    }
    
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
//        Object item = SelectDoctor.getSelectedItem();
//        String doctorId = ((ComboItem)  item).getValue().toString();
//        String complain = ComplaintField.getText();
//        String diagnose = DiagnoseField.getText();
//        double cost =  Double.parseDouble(CostField.getText());
//        PatientCheckup checkup = new PatientCheckup(patientId, doctorId, complain, diagnose, cost);
//        System.out.println("Has id: " + editedId);
//        if (editedId.isEmpty()) {
//            this.patientCheckupService.insert(checkup);
//        } else {
//            checkup.setId(editedId);
//            this.patientCheckupService.update(checkup);
//        }
        refreshTable();
        resetForm();
        JOptionPane.showMessageDialog(this, "Berhasil disimpan!");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        mainFrame.navigate("pasien");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void ResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetFormActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_ResetFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Action;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Form;
    private javax.swing.JPanel Group;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel PatientNameLabel;
    private javax.swing.JButton ResetForm;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
