/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven.app.view;

import com.mycompany.maven.app.ManagePatientCheckup;
import com.mycompany.maven.app.model.PatientCheckup;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.Iterator;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author mac
 */
public class PasienCheckup extends javax.swing.JPanel {
    private PasienPanel pasienPanel;
    private ManagePatientCheckup controller;
    private MainFrame MainFrame;
    /**
     * Creates new form PasienCheckup
     */
    public PasienCheckup(MainFrame frame, PasienPanel pp) {
        initComponents();
        this.controller = new ManagePatientCheckup();

        this.MainFrame = frame;
        this.pasienPanel = pp;
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                System.out.println("Stop");
            }
            @Override
            public void componentShown(ComponentEvent evt) {
                System.out.println("start");
                getDataTable();
                getEditedId();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        Form = new javax.swing.JPanel();
        Group = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        Action = new javax.swing.JPanel();
        ResetForm = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TableConteiner = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCheckups = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Header.setPreferredSize(new java.awt.Dimension(602, 60));
        Header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Pasien Checkup");
        Header.add(jLabel1);

        add(Header, java.awt.BorderLayout.PAGE_START);

        Body.setLayout(new java.awt.BorderLayout());

        Form.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Pasien");

        jLabel3.setText("Doktor");

        jLabel4.setText("Keluhan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(75, 23));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(75, 23));

        jTextField1.setSize(new java.awt.Dimension(75, 23));

        jLabel5.setText("Diagnosa");

        jTextField2.setSize(new java.awt.Dimension(75, 23));

        jLabel6.setText("Biaya");

        jTextField4.setSize(new java.awt.Dimension(75, 23));

        javax.swing.GroupLayout GroupLayout = new javax.swing.GroupLayout(Group);
        Group.setLayout(GroupLayout);
        GroupLayout.setHorizontalGroup(
            GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GroupLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.createSequentialGroup()
                        .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        GroupLayout.setVerticalGroup(
            GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        Form.add(Group, java.awt.BorderLayout.NORTH);

        Action.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        ResetForm.setText("Reset Form");
        ResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetFormActionPerformed(evt);
            }
        });
        Action.add(ResetForm);

        Remove.setText("Hapus pasien");
        Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMouseClicked(evt);
            }
        });
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        Remove.setVisible(false);
        Action.add(Remove);

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        Action.add(Refresh);

        BackButton.setText("Kembali");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Action.add(BackButton);

        jButton1.setText("Simpan");
        Action.add(jButton1);

        Form.add(Action, java.awt.BorderLayout.CENTER);

        Body.add(Form, java.awt.BorderLayout.PAGE_START);

        TableConteiner.setLayout(new java.awt.BorderLayout());

        TableCheckups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Dokter", "Keluhan", "Diagnosa", "Biaya", "dibuat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCheckups.removeColumn(TableCheckups.getColumnModel().getColumn(0));
        jScrollPane1.setViewportView(TableCheckups);

        TableConteiner.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Body.add(TableConteiner, java.awt.BorderLayout.CENTER);

        add(Body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    void getEditedId() {
        System.out.println("edited ID: " + pasienPanel.getEditedId());
    }
    
    public void getDataTable() {
        DefaultTableModel tm = (DefaultTableModel) TableCheckups.getModel();
        tm.setRowCount(0);
        try {
            for (Iterator<PatientCheckup> iterator = this.controller.getAllPatientCheckupPatientId(pasienPanel.getEditedId()).iterator(); iterator.hasNext();) {
                PatientCheckup next = (PatientCheckup) iterator.next();
                System.out.println(next.getId());
                System.out.println(next.getCost());
                System.out.println(next.getPatient().getName());
                Object[] newRow = {
                    next.getId(),
                    next.getDoctor().getName(),
                    next.getPainComplaint(),
                    next.getDiagnose(),
                    next.getCost(),
                    next.getCreatedAt()
                };
                tm.addRow(newRow);
            }
        } catch (HibernateException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    
    private void ResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetFormActionPerformed
        // TODO add your handling code here:
//        resetForm();
    }//GEN-LAST:event_ResetFormActionPerformed

    private void RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseClicked
        // TODO add your handling code here:
//        int confirm = JOptionPane.showOptionDialog(
//            this,
//            "Anda Yakin?",
//            "Hapus",
//            JOptionPane.YES_NO_OPTION,
//            JOptionPane.QUESTION_MESSAGE,
//            null,
//            null,
//            null
//        );
//        if (confirm == JOptionPane.YES_OPTION) {
//            int selectedRow = TablePasien.getSelectedRow();
//            DefaultTableModel pasienModel = (DefaultTableModel) TablePasien.getModel();
//            controller.delete((String) pasienModel.getValueAt(selectedRow, 0));
//            pasienModel.removeRow(selectedRow);
//            JOptionPane.showMessageDialog(this, "Data telah dihapus.");
//        }
    }//GEN-LAST:event_RemoveMouseClicked

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
//        refreshTable();
    }//GEN-LAST:event_RefreshActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        MainFrame.navigate("pasien");
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Action;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Form;
    private javax.swing.JPanel Group;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Remove;
    private javax.swing.JButton ResetForm;
    private javax.swing.JTable TableCheckups;
    private javax.swing.JPanel TableConteiner;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
